### ISSUE TITLE
Hey guys getting this error  on brownie compile           File "brownie/project/sources.py", line 112, in _recursive_inheritance     final |= self._recursive_inheritance(self._data[name]['inherited']) KeyError: 'Token,Betalist'

### ISSUE THREAD

**Issue by deepanshutyagi** [HyperLink-Technology/brownie#135]
* `brownie` Version: x.x.x
* `py-solc-x` Verision: x.x.x
* `solc` Version: x.x.x
* Python Version: x.x.x
* OS: osx/linux/win

### What was wrong?

Please include information like:

* full output of the error you received
* what command you ran
* the code that caused the failure

**Comment by deepanshutyagi** [comment]
looks like brownie cant handle multiple inheritance in solidity

**Comment by iamdefinitelyahuman** [comment]
Hi, thanks for submitting the issue :)

The problem is here:

https://github.com/HyperLink-Technology/brownie/blob/630e02ff1bbf3446b1a0d1765315c5fc4bcc4acf/brownie/project/sources.py#L72

Brownie assumes a space between each inherited contract. Instead of ``is Token,Betalist`` it wants``is Token, Betalist``.

I've fixed this in ``v1.0.0b8`` - the inheritance list is now generated from the AST instead of parsing it directly from the source.  Until the next release is ready though, the easiest solution is to add the space so Brownie parses it correctly.

**Comment by deepanshutyagi** [comment]
ok thanks will change that and get back if there are anymore issues
